# container-based build
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
- 2.12.7

jdk:
- openjdk8

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt +compile
    # run ci-release only if previous stages passed
    - stage: release
      script:
        - eval `cat .secret-enc/env | openssl aes-256-cbc -a -d -md sha256 -k "$SECRET_KEY"`
        - sbt ci-release

script:
  - git fetch --tags
